name: scraping
on:
  workflow_dispatch:

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps firefox
                  
      - name: Run scraper
        run: python main.py
      
      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json *.txt
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
